### ISSUE TITLE
Syntax error type declared in inner scope

### ISSUE THREAD

**Issue by oschulz** [c42f/FastClosures.jl#16]
`@closure` doesn't like this:

```julia
@closure x -> begin
    y::Float64 = 0.0
    y += x
    return y
end
```

results in

```
ERROR: syntax: type of "y" declared in inner scope
```

`@macroexpand` shows the above get's turned into

```julia
let y = y, Float64 = Float64
    x->begin
        # ...
    end
end
```

I guess there's in principle no reason to disallow things like `y::Float64` in a closure, though, right?

**Comment by c42f** [comment]
Thanks I think this is just a bug. `@closure` implements a somewhat nontrivial (if relatively small) subset of julia lowering and I most likely just got it wrong :-)
