### ISSUE TITLE
Register FastClosures.jl?

### ISSUE THREAD

**Issue by JoshChristie** [c42f/FastClosures.jl#3]
Hi,

Was the plan for this package to get registered? 
What needs to be done to get there?

Thanks,

Josh

**Comment by c42f** [comment]
I need to man up, connect CI, and write some docs.

Merging #4 should be sufficient I guess.

**Comment by c42f** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10572

**Comment by c42f** [comment]
Done now.
