### ISSUE TITLE
do block support?

### ISSUE THREAD

**Issue by bramtayl** [c42f/FastClosures.jl#5]
```
"""
    @closure1 e::Expr

Applies closure to the first argument of a function. This is useful for do-block
syntax.
"""
macro closure1(e::Expr)
    if e.head != :call
        error("Must be a function call")
    end
    e.args[2] = :($FastClosures.@closure $(e.args[2]))
    esc(e)
end
```

**Comment by c42f** [comment]
Something like this seems useful. I think we could even build it into `@closure` itself, and have it autodetected:

```
@closure foo() do
    1
end
```

Hmm. The naming of `@closure` is a bit unfortunate in this case.  Any better ideas for a more general name?

**Comment by bramtayl** [comment]
Dunno. `freeze_captures`?

**Comment by c42f** [comment]
The thing is, it doesn't really freeze the captures!  In an effort to preserve the existing semantics, I didn't freeze captures that are assigned to:

```julia
julia> function foo()
           i = 1
           @show i
           c = @closure ()->(i=10; 20)
           c()
           @show i
       end
foo (generic function with 1 method)

julia> foo()
i = 1
i = 10
10
```

But this makes me realize that there's currently a semantic inconsistency - when a capture is used before it's assigned to, it's frozen:

```
julia> function foo()
           i = 1
           @show i
           c = @closure ()->(j=i+1; i=10; 20)
           c()
           @show i
       end
foo (generic function with 1 method)

julia> foo()
i = 1
i = 1
1
```

I guess that's a bug, in the sense that it's very confusing.

So in the effort to be entirely clear about what `@closure` does, maybe the right thing is to just freeze all captures.

Or alternatively, fix the bug above and only freeze captures which are not assigned to.

**Comment by c42f** [comment]
If we went the route of freezing all captures, `@freeze_captures` would be an excellent name.

**Comment by bramtayl** [comment]
Oh I didn't realize that. My two sense would be to go for simpler macro rules.

**Comment by c42f** [comment]
two sense?

...

Oooh.  two *cents* :-P

You mean freezing all captures would be your preferred option?
